-- MySQL Script generated by MySQL Workbench
-- 2020. máj. 21., csütörtök, 14:05:46 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nomk01
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nomk01` ;

-- -----------------------------------------------------
-- Schema nomk01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nomk01` DEFAULT CHARACTER SET utf8mb4 ;
USE `nomk01` ;

-- -----------------------------------------------------
-- Table `nomk01`.`termek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nomk01`.`termek` ;

CREATE TABLE IF NOT EXISTS `nomk01`.`termek` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `termeknev` VARCHAR(100) NOT NULL,
  `egysegar` INT(11) NOT NULL,
  `raktaron` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `termeknev_UNIQUE` (`termeknev` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `nomk01`.`vasarlo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nomk01`.`vasarlo` ;

CREATE TABLE IF NOT EXISTS `nomk01`.`vasarlo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `felhasznalonev` VARCHAR(100) NOT NULL,
  `jelszo` VARCHAR(100) NOT NULL,
  `becsuletes_nev` VARCHAR(100) NOT NULL,
  `szuletesi_datum` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `felhasznalonev_UNIQUE` (`felhasznalonev` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `nomk01`.`kosar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nomk01`.`kosar` ;

CREATE TABLE IF NOT EXISTS `nomk01`.`kosar` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vasarlo_id` INT(11) NOT NULL,
  `termek_id` INT(11) NOT NULL,
  `termek_mennyiseg` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kosar_1_idx` (`vasarlo_id` ASC),
  INDEX `fk_kosar_termek_idx` (`termek_id` ASC),
  CONSTRAINT `fk_kosar_termek`
    FOREIGN KEY (`termek_id`)
    REFERENCES `nomk01`.`termek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kosar_vasarlo`
    FOREIGN KEY (`vasarlo_id`)
    REFERENCES `nomk01`.`vasarlo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 197
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `nomk01`.`vasarlas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nomk01`.`vasarlas` ;

CREATE TABLE IF NOT EXISTS `nomk01`.`vasarlas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idopont` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `vasarlo_becsuletes_neve` VARCHAR(100) NOT NULL,
  `vasarlo_szuletesi_datuma` DATE NOT NULL,
  `termek_id` INT(11) NOT NULL,
  `termek_mennyiseg` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vasarlas_termek_id_idx` (`termek_id` ASC),
  CONSTRAINT `fk_vasarlas_termek_id`
    FOREIGN KEY (`termek_id`)
    REFERENCES `nomk01`.`termek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 125
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
